### ISSUE TITLE
Support Span-based inputs

### ISSUE THREAD

**Issue by LordJZ** [CarlVerret/csFastFloat#39]
Hi, thanks for the lib. Will definitely use it.

Modern performance-oriented C# uses `Span<T>` and friends. It's best to also support `Span<T>` to provide a migration plan for existing users. Supporting `Span<char>` is trivial; supporting UTF-8 with `Span<byte>` is a little bit more work.

**Comment by gfoidl** [comment]
For reference, `Span<char>` is covered by https://github.com/CarlVerret/csFastFloat/issues/50

**Comment by lemire** [comment]
It may be that the latter issue is redundant.

**Comment by lemire** [comment]
I believe that this issue has been resolved, if not, let us reopen it. Closing.
