### ISSUE TITLE
Compare to Utf8Parser

### ISSUE THREAD

**Issue by LordJZ** [CarlVerret/csFastFloat#40]
Utf8Parser and Utf8Formatter are out-of-the-box high-performance number parsers, it would be great to see how this lib performs against them.

**Comment by lemire** [comment]
csFastFloat takes as input what is effectively an array of `char` (16-bit values). If one could assume that the input is ASCII (as would be the case with UTF-8 numbers), then additional optimizations become available.

**Comment by lemire** [comment]
We now have a UTF8-based parser for direct comparisons!
