### ISSUE TITLE
Volume should take into account size (in bytes) of the input or number of characters, but not a mix of both

### ISSUE THREAD

**Issue by lemire** [CarlVerret/csFastFloat#44]
Unless I am mistaken, currently, it seems that the volume (in MB) is computed but assuming that the character span 1 bytes. Of course, char span 2 bytes typically (UTF-16) and so the computation appears to be wrong by a factor of two. Alternatively, one could report the volume in terms of the number of characters.

https://github.com/CarlVerret/csFastFloat/blob/c4dc9004adfbf1dad7659a6f3d6839fbaa9402ce/Benchmark/MFloatPersecColumn.cs#L103

**Comment by CarlVerret** [comment]
fixed !
