### ISSUE TITLE
Submit this code as a patch to the .NET runtime

### ISSUE THREAD

**Issue by IanKemp** [CarlVerret/csFastFloat#48]
That way, any and everyone using .NET will get the speed improvement.

**Comment by lemire** [comment]
+1

cc @EgorBo

**Comment by EgorBo** [comment]
Filed https://github.com/dotnet/runtime/issues/48646

**Comment by CarlVerret** [comment]
Our PR has been merged with runtime. Will be part of the next release (7.x) .
