### ISSUE TITLE
Duplicated ParseNumberString implementations

### ISSUE THREAD

**Issue by lemire** [CarlVerret/csFastFloat#53]
It seems that the library has duplicated functions... if I am correct, then they should be removed... so that the library is leaner...

https://github.com/CarlVerret/csFastFloat/blob/788081cb2bb7a8846096357a15b5a7fe86773a70/csFastFloat/FastFloatParser.cs#L412

**Comment by lemire** [comment]
And now have four of these functions because of the char/byte overloads... So it is a considerable overhead to have all this duplicated code.

**Comment by CarlVerret** [comment]
I'll try to merge them.
