### ISSUE TITLE
Unsafe loads should be guarded with BitConverter.IsLittleEndian or avoided

### ISSUE THREAD

**Issue by lemire** [CarlVerret/csFastFloat#58]
Several of the Unsafe conversions assume a little endian system, so they should be guarded with a check on `BitConverter.IsLittleEndian`. It seems that the JIT compiler is smart enough to realize that endianness does not change over time.

All calls to `Unsafe.ReadUnaligned`,`Unsafe.Copy`, `Buffer.MemoryCopy`.... should be investigated.

In the ASCII branch, this is handled by always failing to recognize 8 characters as 8 digits when `BitConverter.IsLittleEndian` is false. But the rest of the code is less careful.

Note: Hardly anyone has a big endian system these days... so this is really nit picking.

**Comment by gfoidl** [comment]
> It seems that the JIT compiler is smart enough to realize that endianness does not change over time.

It's a `static readonly` fields, so treated as constant, so dead-code elimination is applied.

---

Great catch -- it should be guarded.

**Comment by gfoidl** [comment]
Suggestion based on 

> Hardly anyone has a big endian system these days

Do an upfront check for `BitConverter.IsLittleEndian` (at the method entry of `ParseDouble`), and if LE so use the code in this project. If BE fallback to the .NET provided `double.Parse`.

So this code here can be solely for LE and optimized that way without making chins to handle BE.

**Comment by lemire** [comment]
@gfoidl The guards are easy enough though... The real problem is that hardly anyone has big endian systems so we can't be sure that it will work. Even your simple approach... you may think it works, but then one little typo and it fails. That is, if we can't run rudimentary tests on big endian systems, we can't promise that it will work.

I do not think it is a real problem because we are aware of the issue and it is (now) documented.

**Comment by gfoidl** [comment]
Maybe you got me wrong. I mean something like
```c#
    public static unsafe double ParseDouble(ReadOnlySpan<char> s, chars_format expectedFormat = chars_format.is_general, byte decimal_separator = (byte)'.')
    {
      if (BitConverter.IsLittleEndian)
      { 
        fixed (byte* pStart = s)
        {
          return ParseNumber(pStart, pStart + (uint)s.Length, expectedFormat, decimal_separator);
        }
      }
      else
      {
        return double.Parse(s);
      }
    }
```
So for BE we rely on the .NET implementation.
Only for LE this library-code will be executed, and the checks at the entry are the only ones.

Here we won't have any problem with BE-testing, typos, etc.

**Comment by lemire** [comment]
@gfoidl 

I submit to you the following general principle: you should not agree to support code that you can't run.

Other than that, I did understand your proposal, but I think it is pessimistic. The number of Unsafe.ReadUnaligned instances is low and only a few need to be guarded. It is certainly less than 10.

**Comment by gfoidl** [comment]
> you should not agree to support code that you can't run.

Agree.

Maybe I have the wrong assumption on what we want to achieve with the guard. Did you mean something like
```c#
    public static unsafe double ParseDouble(ReadOnlySpan<char> s, chars_format expectedFormat = chars_format.is_general, byte decimal_separator = (byte)'.')
    {
      if (BitConverter.IsLittleEndian)
      { 
        fixed (byte* pStart = s)
        {
          return ParseNumber(pStart, pStart + (uint)s.Length, expectedFormat, decimal_separator);
        }
      }
      else
      {
        throw new PlatformNotSupported("cfFastFloat is only supported on little-endian platforms.");
      }
    }
```
That's an approach done e.g. in ASP.NET Core's Kestrel server implementation, which uses advanced bit-hacks to only operate on LE.

In general .NET (here: speaking of the runtime / libraries) tries to be more graceful and has a "software-fallback" (documented what are the requirements to run on hardware-accelerated code).

I'm fine either way.

**Comment by lemire** [comment]
@gfoidl I prefer to explain myself with code. Please review https://github.com/CarlVerret/csFastFloat/pull/62 which might fix this issue.
