### ISSUE TITLE
Use .editorconfig

### ISSUE THREAD

**Issue by buybackoff** [CarlVerret/csFastFloat#65]
Please use an .editorconfig file with default settings, or as much as possible close to dotnet/runtime.

It's hard to resist pressing auto-format while working with the code. Two-spaces indent is not common in C# space.

**Comment by CarlVerret** [comment]
I'll provide one soon.  Been working with 2 space indent forever!

**Comment by CarlVerret** [comment]
done!

**Comment by buybackoff** [comment]
> Been working with 2 space indent forever!

I never wanted to start a discussion about formatting. I believe it's over when auto-format exists - just make it work with whatever settings 😄 I mentioned dotnet/runtime because it's very close to defaults and is kind of a reference point.

Just had to press Ctrl-Z couple of times after pressing Сtrl+Alt+L by reflex.
