### ISSUE TITLE
dotnet test will fail when not all SDKs are available

### ISSUE THREAD

**Issue by lemire** [CarlVerret/csFastFloat#70]
If you run the tests of this library on  `mcr.microsoft.com/dotnet/sdk:5.0-focal` image using `dotnet test`, then it fails since [the introduction of a recent commit](https://github.com/CarlVerret/csFastFloat/commit/82198bc3135f2c3d5ee36d4b119eef7c1b39e929), with the following error:

```
Testhost process exited with error: It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '3.1.0' was not found.
```

You can get around the problem by specifying the framework on the command line: `dotnet test --framework net5.0`. That's not ideal: we would want to run the tests on the available frameworks and maybe just issue a warning if a supported warning is not found... but we probably don't want to fail the tests.

The problem will only get worse if we support more frameworks. Of course, you can either require that people who want to run tests have all supported frameworks... or else you ask them to specify their desired framework through a command line.

**Comment by CarlVerret** [comment]
I'll add a Compile section to the readme

**Comment by lemire** [comment]
@CarlVerret Yes, documentation would be one way to solve this issue.
