### ISSUE TITLE
Very minor improvement

### ISSUE THREAD

**Issue by Redageddon** [CarlVerret/csFastFloat#79]
https://github.com/CarlVerret/csFastFloat/blob/master/csFastFloat/Structures/ParsedNumberString.cs#L44

You can replace this with
i *= 10;
i += (ulong)cMinus0;
to reduce one read.

**Comment by lemire** [comment]
Are you saying that...

```C#
i *= 10;
i += (ulong)cMinus0;
```

Compiles to more efficient code than...

```C#
i = 10 * i + (ulong)cMinus0; 
```

?

Can you elaborate?

**Comment by Redageddon** [comment]
It is the same with line 44, 57, 99, 141, 154, 196, 207, 210, 217, 258, 300, 313. Reason: i *= x is not the same as i = i * x and ill leave you with that (hint: its something to do with il emissions)

**Comment by lemire** [comment]
>  Reason: i *= x is not the same as i = i * x and ill leave you with that (hint: its something to do with il emissions)

I invite you to spell out your reasoning.

Meanwhile, let us look at the assembly output.


The following functions...

```C#
    static ulong M1(ulong i, uint c) {
        i *= 10;
        return i + (ulong)c;
    }
    static ulong M2(ulong i, uint c) {
        i = i * 10;
        return i + (ulong)c;
    }
    static ulong M3(ulong i, uint c) {
        return i * 10 + (ulong)c;
    }
```

appear to compile to the following assembly...


```asm
C.M1(UInt64, UInt32)
    L0000: lea rcx, [rcx+rcx*4]
    L0004: shl rcx, 1
    L0007: mov eax, edx
    L0009: add rax, rcx
    L000c: ret

C.M2(UInt64, UInt32)
    L0000: lea rcx, [rcx+rcx*4]
    L0004: shl rcx, 1
    L0007: mov eax, edx
    L0009: add rax, rcx
    L000c: ret

C.M3(UInt64, UInt32)
    L0000: lea rax, [rcx+rcx*4]
    L0004: mov edx, edx
    L0006: lea rax, [rdx+rax*2]
    L000a: ret
```

I would take `M3` over `M1` and `M2`.

Whatever benefit we might get with the suggest approach, it should be possible to demonstrate it with an assembly output.
