### ISSUE TITLE
SIMD approach for parsing of 8 UTF-16 digits should be as efficient as possible

### ISSUE THREAD

**Issue by lemire** [CarlVerret/csFastFloat#84]
We should make sure that the code we use is at least as efficient as the routine in this [StackOverflow answer](https://stackoverflow.com/questions/66371621/hardware-simd-parsing-in-c-sharp-performance-improvement/66430672#66430672):

```C#
public unsafe uint ParseUint(string text)
{
    fixed (char* c = text)
    {
        Vector128<byte> mul1 = Vector128.Create(0x14C814C8, 0x010A0A64, 0, 0).AsByte();
        Vector128<short> mul2 = Vector128.Create(0x00FA61A8, 0x0001000A, 0, 0).AsInt16();
        Vector128<long> shift_amount = Sse2.ConvertScalarToVector128Int32(8 - text.Length << 3).AsInt64();

        Vector128<short> vs = Sse2.LoadVector128((short*)c);
        Vector128<byte> vb = Sse2.PackUnsignedSaturate(vs, vs);
        vb = Sse2.SubtractSaturate(vb, Vector128.Create((byte)'0'));
        vb = Sse2.ShiftLeftLogical(vb.AsInt64(), shift_amount).AsByte();

        Vector128<int> v = Sse2.MultiplyAddAdjacent(Ssse3.MultiplyAddAdjacent(mul1, vb.AsSByte()), mul2);
        v = Sse2.Add(Sse2.Add(v, v), Sse2.Shuffle(v, 1));
        return (uint)v.GetElement(0);
    }
}
```

**Comment by aqrit** [comment]
The `c - '0'` operation could be part of the range check.

The `add(v,v)` can be put into the multiplier, when using int16 instead of int8.

```
	// Pure SSE2.
	// A naive port to NEON should be straight forward (just re-work the conditional).
	__m128i v = _mm_loadu_si128((__m128i*)(void*)src);
	v = _mm_add_epi16(v, _mm_set1_epi16(0x7FC6));
	v = _mm_subs_epi16(v, _mm_set1_epi16(0x7FF6));
	if (_mm_movemask_epi8(v) == 0) { /* has eight UTF-16 LE digits */
		v = _mm_madd_epi16(v, _mm_set_epi16(1, 10, 100, 1000, 1, 10, 100, 1000));
		v = _mm_packs_epi32(v, v);
		v = _mm_madd_epi16(v, _mm_set_epi16(0, 0, 0, 0, 1, 1, 10000, 10000));
		v = _mm_add_epi32(v, _mm_shuffle_epi32(v, 1));
		return (unsigned)_mm_cvtsi128_si32(v);
	}
```

I'd like credit if y'all use the "shift off the bad chars method".
but otherwise I don't need (or want) credit for something this simple.

I wonder if using `pmuludq` would allow the multiplies to run in parallel...

**Comment by CarlVerret** [comment]
Been trying to benchmark the two approches  (eval1 & eval2)

simplified version in which range check is omited 

eval1 : 
-----
      Vector128<short> raw = Sse41.LoadDquVector128((short*)start);
      Vector128<short> mask0 = Vector128.Create((short)48); // adapter à la longueur
      raw = Sse41.SubtractSaturate(raw, mask0);
      Vector128<short> mul0 = Vector128.Create(10, 1, 10, 1, 10, 1, 10, 1);
      Vector128<int> res = Sse41.MultiplyAddAdjacent(raw.AsInt16(), mul0);
      Vector128<int> mul1 = Vector128.Create(1000000, 10000, 100, 1);
      res = Sse41.MultiplyLow(res, mul1);
      Vector128<int> shuf = Sse41.Shuffle(res, 0x1b); // 0 1 2 3 => 3 2 1 0
      res = Sse41.Add(shuf, res);
      shuf = Sse41.Shuffle(res, 0x41); // 0 1 2 3 => 1 0 3 2
      res = Sse41.Add(shuf, res);
      value = (uint)res.GetElement(0);

eval2 : 
-----
      Vector128<short> raw = Sse41.LoadDquVector128((short*)start);
      Vector128<byte> mul1 = Vector128.Create(0x14C814C8, 0x010A0A64, 0, 0).AsByte();
      Vector128<short> mul2 = Vector128.Create(0x00FA61A8, 0x0001000A, 0, 0).AsInt16();
      Vector128<byte> vb = Sse2.PackUnsignedSaturate(raw, raw);
      vb = Sse2.SubtractSaturate(vb, Vector128.Create((byte)'0'));
      Vector128<int> v = Sse2.MultiplyAddAdjacent(Ssse3.MultiplyAddAdjacent(mul1, vb.AsSByte()), mul2);
      v = Sse2.Add(Sse2.Add(v, v), Sse2.Shuffle(v, 1));
      value = (uint)v.GetElement(0);

here's the result I obtain for 850 000 random 8 digit numbers

|      Method |     Mean |     Error |    StdDev |   Median | Ratio | RatioSD |
|------------ |---------:|----------:|----------:|---------:|------:|--------:|
| EvalParse_1 | 6.381 ms | 0.1258 ms | 0.2625 ms | 6.394 ms |  1.00 |    0.00 |
| EvalParse_2 | 6.338 ms | 0.1518 ms | 0.4331 ms | 6.181 ms |  1.02 |    0.08 |

Looks like pretty close performance for both.

**Comment by aqrit** [comment]
It is a micro-optimization.  The difference between EvalParse_1 and EvalParse_2 is 5 cycles of latency and 1 uop.
A EvalParse_2 without the `add(v,v)` saves an additional 1 uop, but has the same latency.  The split multiply version saves ~3 cycles of latency at the cost of ~3 uops.

An improved range check saves 1 cycle of latency and 1 uop.
