### ISSUE TITLE
Custom decimal separator

### ISSUE THREAD

**Issue by albertony** [CarlVerret/csFastFloat#96]
Is `decimal_separator` argument not working as intended?

Parsing `"397,72"` with `FastFloatParser.TryParseFloat` and argument `decimal_separator: ','` results in value `397`. I would expect it to be able to parse the decimals as well: `397.72`.

Parsing `"397.72"` with `FastFloatParser.TryParseFloat` and argument `decimal_separator: ','` results in value `397.72`. I would expect it to only parse the int part `397`.

Is there a reason why the call to helper function `ParseNumberString` does not pass along the decimal_separator argument:

https://github.com/CarlVerret/csFastFloat/blob/76d6a2e76a6d3c1f90a7f4b9747661979158e7e4/csFastFloat/FastDoubleParser.cs#L468

**Comment by CarlVerret** [comment]
Thanks for pointing that, I'll fix it promptly.

**Comment by CarlVerret** [comment]
Fixed in release 4.1
